server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=America/New_York&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml



# 微信公众号对接
weixin:
  config:
    originalid: gh_db9aec6fcfc2
    token: b8b6
    app-id: wx82a7dcc7ff7363c1
    app-secret: f7f05d198d6ec4b03d816c0ab742a9a6
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y
    #accessToken: 94_L18wLaPdzQfM2ExFrkOKJSVE6yg6DEIPHzaD20E2UGxTWiKH2s8zb7lO1k5r2LsN_JrB8F1YUyEro9DuH6_THpt-eh4vToBoIVncBzXAclLcgnkPuvAzwuQn0pQCSEbACAGWI  # ⚠️ 使用你自己的 access_token（有效期2小时）

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000150643661
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbG2PKCJZ0rMRfAVahesN9vh9ZQqWGwS9Z09jbC1yX3/LAUuIPoXMYrgl9qku+ClSIJ0dddqJdJ7Q0kXZvDtvPSndeQcjuPnzdlV7IBuiwIwb5KxwrFGpo0o+jFsra1LEoclJDaIjy7PletaSf52XqZzDhz0LAv+svSdvOHe9BILnAbenJvJI53IJPHwz/ITJzXcq86ilqD5zfPqzFgD4I23Dde6zOI5OS99vnd66wJEU3xXXxvspYu5N+/xVteHeDM+XkSW2KZlG4IxMuL8CbguXV0WoDv2sKB9SGSXGYt/zZ/TRrZGgHOTe+Gc5saCsdQwtcsruIrOr7Gei0wfp3AgMBAAECggEAJbdDTJ1J+JUKKw/oQNvZLXpNpSbPmTTgjrc0xA6/NS7/mESPM73OfvHS3PvL7yoT5AepEtEGKiC9cQruAZNbX8x7ui/E7CnFsxvfMER90Fa0G2KgNtmABn0s8DtamFufuHYUCtAgfPGisaT5ouhhn933xPDhCn2gcp9DE5uz0eIAXGN2pFiXcx5YcAjnm39MVMNXVdFHYhrXszR4RZCeghqkGd5DHKYc4DjKfGeB16MW8y2i5o0Za9zDQEeidJ+aHQFUcdqeGgMv4idl05pFAa8KMBHyxZ9wAfmQHUdh8sOu1FLCUoGuHe18CFkySZIGU/d/d1kJLrCOt3qPSwmOAQKBgQD0QlugCVOY0T1ccxB0ZH8jBbhOAwyyMXmetIqPwm7pyKE7bI8tWFUfUBQZ0J3wDwC+nuxMiXjBwiBkH6f0gkLJZDf9dbA5eqOVx4+/6Hln3nALGyYlKv44TJ6BTBcsKqCe+1hcBaC5QmwKalCXc6PSNZXXh73uWf8CQs53YgIF/QKBgQCikACBJOucsMDj1FMZj7oYW+qwwXAERm3++CFsRcCOjXIkJdVp85of2rPHZ0SyTkvm4cVF3sN2tZt00Uk0g1ZX0GgX7ltCo0YsbqjJledM+vPSASgjkYW7+F/IELHFApAk8BiogXWJP7tIOLbLfVL/4IPECw13uZM4RP9A6XuygwKBgQDwBJDihqel394rDUpbBTHFKWa9CdQc+e7nm8MYltfEVIjSys86oLUsitTltRCthyCVL7dFUkTeKLMJj+3Ln4CfQyKdplrfcHp0wN+plXhPL83rq+bk2QVsLyYGKc4PcWfaMWPXMRSJVxKxfVzqJhERi+RNIS7qm3axMxKNTzprxQKBgGYHdZmYv5xnv5j/EW0QrV9OiX2I2zKDtdP6jpezK8kM89/GMy09rLVjgcSchxxWUgNGHpfc2ddu4nQuSwD/kbip4Dts6bBoY8nNZnincjX5qABdo4C3fDVfDVa3S6v4ENpuKzvPjSKocnZAylHrhaV9l5X6zegf/Eur2n02TeHbAoGAR+HXewCq11dqah3JsJIHiv8QogmpehUN+giPekCDP6CTHD5ZJjHhFZnYk8s1D0QnG5xdLhAYIxy4Rzr8pLebShhzXNZu/Cv55LgppA6oZ4yfObxNb8oqAOxHfU/S4X29/ohNYwgMJ8kvqtdce+bcuAyezV+c6V3q0mEchM+Oz+s=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv6qcU+5vG7RODk/1+6rDcfXyTE+p/aIMVvZIsZErOcG1LQDU9hem6DHCNZUYPEQ1PYzjqSnh5N1acC1jA7nB3Zvnupm69PdREvDcntucK3OamYKsJDlYNupgepjwMiBfNFncja+ZNNfoNE9WdDHrcUAd2PGZuFTO9FV5njAh9pnVeqlgehAOm/nWD7P9xyjWplD3VYalVo04PjRdEQq7OWTUCE51NuHIYpP9+J4fy48jxi8PvsRQO+cmhUjRHbop6jIwMt8sA81wAHO6SgBjPQ5jO+X6hJqef825VigaEhAQGgPA/SCUwh+R3grm6EVd06c/UEJ3IBhIGLadcvee1QIDAQAB
  notify_url: http://songhan.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://github.com/nininini820/s-pay-mall-mvc-songhan
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml